# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:15:02+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, RootModel


class Asset(BaseModel):
    key: Optional[str] = None
    label: Optional[str] = None
    length: Optional[int] = None


class Contact(BaseModel):
    emailAddress: Optional[str] = None
    fullName: Optional[str] = None
    mobileNumber: Optional[str] = None
    phoneNumber: Optional[str] = None


class DataModel(BaseModel):
    key: Optional[str] = None
    timestamp: Optional[datetime] = None


class DocumentContact(BaseModel):
    details: Optional[str] = None
    title: Optional[str] = None


class Edition(DataModel):
    htmlBody: Optional[str] = None
    name: Optional[str] = None


class EditionImage(DataModel):
    fileName: Optional[str] = None
    imageBytes: Optional[str] = None
    imageType: Optional[str] = None


class FacebookPost(DataModel):
    content: Optional[str] = None
    facebookObjectId: Optional[int] = None
    pictureUri: Optional[str] = None
    postComments: Optional[int] = None
    postLikes: Optional[int] = None
    postShares: Optional[int] = None
    poster: Optional[str] = None
    posterLikes: Optional[int] = None
    posterLogo: Optional[str] = None
    posterSubtitle: Optional[str] = None
    type: Optional[str] = None


class KeyValuePair2(BaseModel):
    key: Optional[str] = None
    value: Optional[str] = None


class Minister(DataModel):
    details: Optional[str] = None
    emailHtml: Optional[str] = None
    headline: Optional[str] = None
    photo: Optional[str] = None
    post: Optional[str] = None
    summary: Optional[str] = None


class Newsletter(DataModel):
    description: Optional[str] = None
    editions: Optional[List[KeyValuePair2]] = None
    ministryName: Optional[str] = None
    name: Optional[str] = None


class ResourceLink(DataModel):
    uri: Optional[str] = None


class Slide(DataModel):
    actionLabel: Optional[str] = None
    actionUri: Optional[str] = None
    facebookPostUri: Optional[str] = None
    headline: Optional[str] = None
    image: Optional[str] = None
    imageType: Optional[str] = None
    justify: Optional[str] = None
    slideId: Optional[UUID] = None
    summary: Optional[str] = None


class ApiNewslettersGetResponse(RootModel[List[Newsletter]]):
    root: List[Newsletter]


class PostKeys(RootModel[List[str]]):
    root: List[str]


class ApiPostsKeysIndexKindIndexKeyGetResponse(RootModel[List[KeyValuePair2]]):
    root: List[KeyValuePair2]


class ApiResourceLinksGetResponse(RootModel[List[ResourceLink]]):
    root: List[ResourceLink]


class ApiSlidesGetResponse(RootModel[List[Slide]]):
    root: List[Slide]


class Article(DataModel):
    editionName: Optional[str] = None
    htmlBody: Optional[str] = None


class DataIndex(DataModel):
    featurePostKey: Optional[str] = None
    kind: Optional[str] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None


class Document(BaseModel):
    byline: Optional[str] = None
    contacts: Optional[List[DocumentContact]] = None
    detailsHtml: Optional[str] = None
    headline: Optional[str] = None
    languageId: Optional[int] = None
    pageTitle: Optional[str] = None
    subheadline: Optional[str] = None


class Home(DataIndex):
    featurePostKey: Optional[str] = None
    liveWebcastFlashMediaManifestUrl: Optional[str] = None
    liveWebcastM3uPlaylist: Optional[str] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None


class Post(DataModel):
    assetUrl: Optional[str] = None
    atomId: Optional[str] = None
    azureAssets: Optional[List[Asset]] = None
    documents: Optional[List[Document]] = None
    facebookPictureUri: Optional[str] = None
    hasMediaAssets: Optional[bool] = None
    isNewsOnDemand: Optional[bool] = None
    keywords: Optional[str] = None
    kind: Optional[str] = None
    leadMinistryKey: Optional[str] = None
    location: Optional[str] = None
    ministryKeys: Optional[List[str]] = None
    publishDate: Optional[datetime] = None
    redirectUri: Optional[str] = None
    reference: Optional[str] = None
    sectorKeys: Optional[List[str]] = None
    serviceKeys: Optional[List[str]] = None
    socialMediaHeadline: Optional[str] = None
    socialMediaSummary: Optional[str] = None
    summary: Optional[str] = None


class ApiPostsGetResponse(RootModel[List[Post]]):
    root: List[Post]


class ApiPostsLatestIndexKindIndexKeyGetResponse(RootModel[List[Post]]):
    root: List[Post]


class Category(DataIndex):
    audioUri: Optional[str] = None
    featurePostKey: Optional[str] = None
    flickrUri: Optional[str] = None
    isActive: Optional[bool] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None
    twitterFeedUsername: Optional[str] = None
    youtubeUri: Optional[str] = None


class Ministry(Category):
    audioUri: Optional[str] = None
    childMinistryKey: Optional[str] = None
    contactUser: Optional[Contact] = None
    displayAdditionalName: Optional[str] = None
    featurePostKey: Optional[str] = None
    flickrUri: Optional[str] = None
    isActive: Optional[bool] = None
    ministerName: Optional[str] = None
    ministryUrl: Optional[str] = None
    name: Optional[str] = None
    newsletterLinks: Optional[List[ResourceLink]] = None
    parentMinistryKey: Optional[str] = None
    secondContactUser: Optional[Contact] = None
    serviceLinks: Optional[List[ResourceLink]] = None
    topPostKey: Optional[str] = None
    topicLinks: Optional[List[ResourceLink]] = None
    twitterFeedUsername: Optional[str] = None
    weekendContactNumber: Optional[str] = None
    youtubeUri: Optional[str] = None


class Sector(Category):
    audioUri: Optional[str] = None
    featurePostKey: Optional[str] = None
    flickrUri: Optional[str] = None
    isActive: Optional[bool] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None
    twitterFeedUsername: Optional[str] = None
    youtubeUri: Optional[str] = None


class Service(Category):
    audioUri: Optional[str] = None
    featurePostKey: Optional[str] = None
    flickrUri: Optional[str] = None
    isActive: Optional[bool] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None
    twitterFeedUsername: Optional[str] = None
    youtubeUri: Optional[str] = None


class Tag(Category):
    audioUri: Optional[str] = None
    featurePostKey: Optional[str] = None
    flickrUri: Optional[str] = None
    isActive: Optional[bool] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None
    twitterFeedUsername: Optional[str] = None
    youtubeUri: Optional[str] = None


class Theme(Category):
    audioUri: Optional[str] = None
    featurePostKey: Optional[str] = None
    flickrUri: Optional[str] = None
    isActive: Optional[bool] = None
    name: Optional[str] = None
    topPostKey: Optional[str] = None
    twitterFeedUsername: Optional[str] = None
    youtubeUri: Optional[str] = None


class ApiMinistriesGetResponse(RootModel[List[Ministry]]):
    root: List[Ministry]


class ApiSectorsGetResponse(RootModel[List[Sector]]):
    root: List[Sector]


class ApiServicesGetResponse(RootModel[List[Service]]):
    root: List[Service]


class ApiTagsGetResponse(RootModel[List[Tag]]):
    root: List[Tag]


class ApiThemesGetResponse(RootModel[List[Theme]]):
    root: List[Theme]
